### ISSUE TITLE
Dependency question/request

### ISSUE THREAD

**Issue by tjsego** [dilpath/mkstd#1]
Is it possible to downgrade the `pydantic-numpy` major version requirement to 5.x? 6.x introduced a numpy 2.x requirement that excludes some target projects (*e.g.*, [libRoadRunner](https://github.com/sys-bio/roadrunner)) for [libSSR](https://github.com/tjsego/libSSR).

**Comment by dilpath** [comment]
It looks like the next version of libRoadRunner will require numpy 2.x
https://github.com/sys-bio/roadrunner/pull/1236

I agree though, it's suboptimal that numpy 1.x is unsupported due to this... I'll take another look at the options for type annotations of numpy objects with pydantic.

**Comment by dilpath** [comment]
Fixed in `mkstd==0.0.5`, by installing with e.g. `pip install mkstd[numpyv1]`. `pip install mkstd` will default to the latest versions of `pydantic-numpy` and `numpy`.
